### PR TITLE
fix(node:async_hooks): remove extra methods from `AsyncHook` class

### LINKED ISSUE #403: `async_hooks.AsyncHook` hooks has extra methods
### Environment

N/A

### Reproduction

https://github.com/unjs/unenv/blob/ada7c4093c69c9729f1b008a8ab7902389941624/src/runtime/node/async_hooks/internal/async-hook.ts#L25

AsyncHook class should not have functions that should be defined in async hook callbacks. Specifically any methods except enable and disable should be removed.

### Describe the bug

async_hook polyfill is wrong.

### Additional context

_No response_

### Logs

```sh

```

### PR DESCRIPTION
**Pull request by pi0**
resolves #403

### CODE REVIEW

**Review by anonrig — APPROVED** [review]

File: src/runtime/node/internal/async_hooks/async-hook.ts [hunk 1]
```diff
@@ -22,34 +24,24 @@ class _AsyncHook implements asyncHooks.HookCallbacks {
     return this;
   }
 
-  init(asyncId: number, type: string, triggerAsyncId: number, resource: any) {
-    if (this._enabled && this._callbacks.init) {
-      this._callbacks.init(asyncId, type, triggerAsyncId, resource);
-    }
+  get [Symbol("init")]() {
```
Comment (vicb) [inline src/runtime/node/internal/async_hooks/async-hook.ts:27]: Shouldn't that be `Symbol.for()`?

Comment (vicb) [reply src/runtime/node/internal/async_hooks/async-hook.ts:27]: I looked into this:
Node uses `Symbol("...")` and has a ref in internal.

I think that having `[Symbol(...)]` makes the code unreachable? Is that what we want here? (maybe to satisfy the type).

Comment (pi0) [reply src/runtime/node/internal/async_hooks/async-hook.ts:27]: Yeah same situation as Node (i wish they used `Symbol.for` we have so many issues with this always)

My goal was mainly semantic. it doesn't really matter for private symbols I guess.
